// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NETCOREM3_CodeFirst.Models;

namespace NETCOREM3_CodeFirst.Migrations
{
    [DbContext(typeof(CarDBContext))]
    [Migration("20201116171722_Vehiculo-Fecha")]
    partial class VehiculoFecha
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NETCOREM3_CodeFirst.Models.Vehiculo", b =>
                {
                    b.Property<int>("vehiculoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("vehiculoFecha")
                        .HasColumnType("Date");

                    b.Property<string>("vehiculoMarca")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vehiculoModelo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("vehiculoPlaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("vehiculoID");

                    b.ToTable("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
